export const SET_TO_DAY_ANIMALS = 'SET_TO_DAY_ANIMALS';
export const REMOVE_TO_DAY_ANIMALS = 'REMOVE_TO_DAY_ANIMALS';
export const SET_ALL_ANIMALS = 'SET_ALL_ANIMALS';
export const REMOVE_ALL_ANIMALS = 'REMOVE_ALL_ANIMALS';